version: '3.7'
services:
  master:
    image: burtsevyg/jenkins
    environment:
      - JAVA_OPTS=-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false
      - JENKINS_SLAVE_AGENT_PORT=50000
    volumes:
      - jenkins_home:/var/jenkins_home
    ports:
    - '8080:8080'
    - '50000:50000'
    networks:
      - frontend
      - backend
networks:
  frontend:
  backend:
volumes:
  jenkins_home:

